
mybatis-plus:
  mapper-locations: classpath:mapper/*Mapper.xml
#  type-aliases-package: com.zhouheng.commybatisplus.model
  global-config:
    db-config:
      id-type: auto
      field-strategy: ignored
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    jdbc-type-for-null: null
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.93.4.127:3306/zhouheng?characterEncoding=utf8&characterSetResults=utf8&autoReconnect=true&failOverReadOnly=false
    username: root
    password: 123456