

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.146.128:3306/zhouheng?characterEncoding=utf8&characterSetResults=utf8&autoReconnect=true&failOverReadOnly=false
    username: root
    password: zh257405
    max-wait: 1200000



zhouheng:
  muti-datasource-open : true
  muti-baokao-datasource:
    default-dataSource-name: dataSourceZhouheng #默认的数据源名称
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.146.128:3306/zhouheng?characterEncoding=utf8&characterSetResults=utf8&autoReconnect=true&failOverReadOnly=false
    username: root
    password: zh257405

